#ifndef _ASSERVISSEMENT_DEPORTE_FACTEURS_CONVERSION_H_
#define _ASSERVISSEMENT_DEPORTE_FACTEURS_CONVERSION_H_

#define CONV_ANGLE2MESSAGE      (1000.)
#define CONV_DISTANCE2MESSAGE   (10.)
#define CONV_CDEMOTEUR2MESSAGE  (100.)

#endif // _ASSERVISSEMENT_DEPORTE_FACTEURS_CONVERSION_H_
